server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: Xkai112305

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.singed.springcloud.entities    # 所有Entity别名类所在包